name: App Workflow

on:
  push:
      branches:
        - main
jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
#      https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Composer Install
        run: sh ./.github/scripts/run-composer.sh
      - name: TDD PHPUnit
        run: sh ./.github/scripts/run-phpunit.sh
      - name: Conexão SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: |
            cd /var/www/html/williamreis/actions-teste
            git checkout main
            git pull